# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EnviroCarHotSpotAnalysis
                                 A QGIS plugin
 This plugin is developed for detect the hotspots of enviro car data set measurements based on getisord method
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-05-07
        copyright            : (C) 2020 by Prasadi Senadeera and David Payares
        email                : jprasadi4u@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EnviroCarHotSpotAnalysis class from file EnviroCarHotSpotAnalysis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .EnviroCarHotSpotAnalysis import EnviroCarHotSpotAnalysis
    return EnviroCarHotSpotAnalysis(iface)
